
# This is example usage of simple-provisioner.yml
- include: simple-provisioner.yml
  when: pubkey is defined
  # from here, you can build out your playbook as normal

- hosts: "{{target}}"
  tasks:
  - raw: touch sudoing_with_ansible
